# Generated by Django 6.0.3 on 2026-03-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flightsession",
            options={"ordering": ["-start_time"]},
        ),
        migrations.AlterModelOptions(
            name="mission",
            options={"ordering": ["site__name", "name"]},
        ),
        migrations.AlterModelOptions(
            name="missionlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="site",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="waypoint",
            options={"ordering": ["mission", "order_index"]},
        ),
        migrations.AlterModelOptions(
            name="zone",
            options={"ordering": ["site__name", "name"]},
        ),
        migrations.AlterField(
            model_name="flightsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("planned", "Planned"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="trigger_type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("event", "Event")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="waypoint",
            name="order_index",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="waypoint",
            constraint=models.UniqueConstraint(
                fields=("mission", "order_index"),
                name="unique_waypoint_order_per_mission",
            ),
        ),
    ]
