# Generated by Django 6.0.3 on 2026-03-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_flightsession_options_alter_mission_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="current_waypoint_index",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
